### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by hemant4524** [francescocervone/RxDrive#1]
I want to get root folder list. Using below code but getting null pointer exception

```

mRxDrive.listChildren(mRxDrive.getRootFolder())
                        .subscribe(new Action1<List<DriveId>>() {
                            @Override
                            public void call(List<DriveId> driveIds) {

                                Log.d(TAG, "driveIds size:"+driveIds.size());
                            }
                        }, new Action1<Throwable>() {
                            @Override
                            public void call(Throwable throwable) {
                                Log.d(TAG, "driveIds size:"+throwable.getMessage()); }
                        });

```

**Comment by francescocervone** [comment]
Can you please paste the stacktrace?
Thanks

**Comment by hemant4524** [comment]
`driveIds size:Attempt to invoke interface method 'com.google.android.gms.common.api.PendingResult com.google.android.gms.drive.DriveFolder.listChildren(com.google.android.gms.common.api.GoogleApiClient)' on a null object reference`

**Comment by hemant4524** [comment]
I want to display all images in google drive.

**Comment by francescocervone** [comment]
Ok.
Try using the [constructor with GoogleApiClient Builder](https://github.com/francescocervone/RxDrive/blob/master/rxdrive/src/main/java/com/francescocervone/rxdrive/RxDrive.java#L77), passing `SCOPE_FILE` as scope in the builder.
Please let me know if it fixes the NPE.
Thanks.

**Comment by hemant4524** [comment]
Now above code is run. But i can't achieve my goal. I want to display all images from google drive.

**Comment by francescocervone** [comment]
Fixed https://github.com/francescocervone/RxDrive/commit/cb6adc907e0388a5fc95a9a0d4c2d7d06951268e
