### ISSUE TITLE
App is not listing childrens after uninstallation and reinstallation

### ISSUE THREAD

**Issue by F4bioo** [francescocervone/RxDrive#5]
Hello, My app not listing children after uninstalling and reinstalling.

This ploblema is known issue and is in Google Service [here](http://stackoverflow.com/a/26541855/5392773)

The user [Daniel](http://stackoverflow.com/users/418111/daniel) (Product Manager at Google) said: "we recommend using requestSync () to ensure App Folder content is synced before attempting to restore."

Is there any way to use requestSync() in your library?

**Comment by francescocervone** [comment]
Yes. Actually this is possible in the develop branch. You can find a method `sync()` in the `RxDrive` class.
I should update the library.

**Comment by francescocervone** [comment]
#4

**Comment by francescocervone** [comment]
Released: version [0.2](https://github.com/francescocervone/RxDrive/releases/tag/0.2)

**Comment by F4bioo** [comment]
It's working like a charm now. I think you should update the readme description to v0.2.
Thanks a lot for your library. ^^
